### ISSUE TITLE
when l using 'run' Command ，

### ISSUE THREAD

**Issue by Louisees** [zerosum0x0/koadic#40]
(koadic: sta/js/mshta)# run
Traceback (most recent call last):
  File "/data/git/koadic/core/shell.py", line 37, in run
    self.run_command(cmd)
  File "/data/git/koadic/core/shell.py", line 67, in run_command
    self.actions[action].execute(self, cmd)
AttributeError: module 'run' has no attribute 'execute'

python version:  3.5.3
System version: CentOS release 6.9 (Final)

l dont know .  what's wrong.....

**Comment by TheNaterz** [comment]
Well that's definitely interesting. Can you confirm the presence of run.py located under core/commands and can you confirm that the execute function is in run.py? We know that it works with python 3.5.2, but we'll look into it.
